version: "3.8"
services:
  todo-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-api-server
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - JWT_SECRET=$JWT_SECRET
      - TOKEN_EXPIRATION=$TOKEN_EXPIRATION
      - POSTGRES_HOST=postgres-db
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - .pgdata/prod:/var/lib/postgresql/data
